g308_isaacgym:
  model_name: "him_km3_0324_01(10good).pt" # him_km3_0315_02(5good).pt
  crawl_name: "him_crawl_km3_0324_01(10good).pt"
  jump_name: "xiaotiao.pt"
  framework: "isaacgym"
  rows: 4
  cols: 3
  dt: 0.005
  decimation: 4
  num_observations: 45
  # observations: ["ang_vel", "gravity_vec", "commands", "dof_pos", "dof_vel", "actions"]
  observations: ["commands", "ang_vel", "gravity_vec", "dof_pos", "dof_vel", "actions"]
#   observations_history: [5, 4, 3, 2, 1, 0] #--0219  0306-- 0313
  observations_history: [10,9,8,7,6,5, 4, 3, 2, 1, 0] #0219 #0315
  clip_obs: 100.0
  clip_actions_lower: [-100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100,
                       -100, -100, -100]
  clip_actions_upper: [100, 100, 100,
                       100, 100, 100,
                       100, 100, 100,
                       100, 100, 100]
  rl_kp: [40., 40., 50.,
          40., 40., 50.,
          40., 40., 40., #40.
          40., 40., 40.] #40.
  # rl_kp: [50., 50., 50.,
  #         50., 50., 50.,
  #         50., 50., 50.,
  #         50., 50., 50.] #40.
  rl_kd: [1., 1., 1.,
          1., 1., 1.,
          1., 1., 1., # 1.
          1., 1., 1.] # 1.
  fixed_kp: [100., 300., 300.,
             100., 300., 300.,
             100., 300., 300.,
             100., 300., 300.]
  fixed_kd: [5.,8.,8.,
             5.,8.,8.,
             5.,8.,8.,
             5.,8.,8.]
  hip_scale_reduction: 1.  # 0.5 0213
  hip_scale_reduction_indices: [0, 3, 6, 9]
  num_of_dofs: 12
  action_scale: 0.25
  lin_vel_scale: 2.0
  ang_vel_scale: 0.25
  dof_pos_scale: 1.0
  dof_vel_scale: 0.05
  commands_scale: [2.0, 2.0, 0.25] # 2. 2. 1.
  torque_limits: [20, 20, 20,
                  20, 20, 20,
                  20, 20, 20,
                  20, 20, 20]
#   default_dof_pos: [ -0.0, 0.7, -1,
#                      0.0, 0.7, -1,
#                      -0.0, 0.7, -1,
#                      0.0, 0.7, -1] # km2
  default_dof_pos: [ -0.0, 0.7, -1.5,
                     0.0, 0.7, -1.5,
                     -0.0, 0.7, -1.5, 
                     0.0, 0.7, -1.5] # 0312-0313 0. 0.9 -1.5
  # default_dof_pos: [ 0.0, 0.7, -0.8,
  #                    0.0, 0.7, -0.8,
  #                    0.0, 0.7, -0.8,
  #                    0.0, 0.7, -0.8] # 0220--0224
  joint_controller_names: ["FL_hip_controller", "FL_thigh_controller", "FL_calf_controller",
                           "FR_hip_controller", "FR_thigh_controller", "FR_calf_controller",
                           "RL_hip_controller", "RL_thigh_controller", "RL_calf_controller",
                           "RR_hip_controller", "RR_thigh_controller", "RR_calf_controller"]
