horse2:

  # publish all joints
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  # position Controllers
  # p 根据误差来调整 i 消除稳态误差 d 避免过冲
  # D 值过高可能导致系统对噪声过于敏感，变得不稳定 D 值过低可能使系统过冲较大，产生较长时间的振荡。
  # I 值过高可能导致系统积分饱和，出现过冲和振荡 I 值过低可能使系统无法完全消除误差，无法精确达到目标值。
  # P 值过高可能导致系统过度调节，出现振荡或不稳定 P 值过低可能导致系统响应迟钝，达不到目标
  
  #zuohou
  zuohou1j_position_controller:
    type: effort_controllers/JointPositionController 
    joint: zuohou1j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuohou2j_position_controller:
    type: effort_controllers/JointPositionController
    joint: zuohou2j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuohou3j_position_controller:
    type: effort_controllers/JointPositionController
    joint: zuohou3j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  # zuoqian
  zuoqian1j_position_controller:
    type: effort_controllers/JointPositionController
    joint: zuoqian1j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuoqian2j_position_controller:
    type: effort_controllers/JointPositionController
    joint: zuoqian2j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuoqian3j_position_controller:
    type: effort_controllers/JointPositionController
    joint: zuoqian3j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  # youhou
  youhou1j_position_controller:
    type: effort_controllers/JointPositionController
    joint: youhou1j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youhou2j_position_controller:
    type: effort_controllers/JointPositionController
    joint: youhou2j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youhou3j_position_controller:
    type: effort_controllers/JointPositionController
    joint: youhou3j
    pid: {p: 100.0,i: 0.01,d: 1.0}
    
  #youqian
  youqian1j_position_controller:
    type: effort_controllers/JointPositionController
    joint: youqian1j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youqian2j_position_controller:
    type: effort_controllers/JointPositionController
    joint: youqian2j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youqian3j_position_controller:
    type: effort_controllers/JointPositionController
    joint: youqian3j
    pid: {p: 100.0,i: 0.01,d: 1.0}
