horse2:
  
  # publish all joints
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100

  #zuohou
  zuohou1j_position_controller:
    type: effort_controllers/JointEffortController
    joint: zuohou1j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuohou2j_position_controller:
    type: effort_controllers/JointEffortController
    joint: zuohou2j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuohou3j_position_controller:
    type: effort_controllers/JointEffortController
    joint: zuohou3j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  # zuoqian
  zuoqian1j_position_controller:
    type: effort_controllers/JointEffortController
    joint: zuoqian1j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuoqian2j_position_controller:
    type: effort_controllers/JointEffortController
    joint: zuoqian2j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  zuoqian3j_position_controller:
    type: effort_controllers/JointEffortController
    joint: zuoqian3j
    pid: {p: 100.0,i: 0.01,d: 2.0}

  # youhou
  youhou1j_position_controller:
    type: effort_controllers/JointEffortController
    joint: youhou1j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youhou2j_position_controller:
    type: effort_controllers/JointEffortController
    joint: youhou2j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youhou3j_position_controller:
    type: effort_controllers/JointEffortController
    joint: youhou3j
    pid: {p: 100.0,i: 0.01,d: 1.0}
    
  #youqian
  youqian1j_position_controller:
    type: effort_controllers/JointEffortController
    joint: youqian1j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youqian2j_position_controller:
    type: effort_controllers/JointEffortController
    joint: youqian2j
    pid: {p: 100.0,i: 0.01,d: 1.0}

  youqian3j_position_controller:
    type: effort_controllers/JointEffortController
    joint: youqian3j
    pid: {p: 100.0,i: 0.01,d: 1.0}
